### ISSUE TITLE
The plugin does not support tables

### ISSUE THREAD

**Issue by jdnichollsc** [hectorguo/CKEditor-Markdown-Plugin#1]
Hi man,

I created a table but this does not convert to markdown

Thanks in advance, Nicholls

**Comment by hectorguo** [comment]
Yes，it is a tough one, table html to markdown format is not easy to transfer. 

However, compared with WYSIWYG mode, editing table in markdown is not user-friendly, so when our team need to use some tables, we will edit them in WYSIWYG mode,  it is more easy to edit, right? 

Finally, we mainly use content in html format rather than markdown. 
Hope you could understand. :smiley:

**Comment by mkurz** [comment]
+1

**Comment by wilkolazki** [comment]
+1

**Comment by FrancescJR** [comment]
hey, I am confused. Actually markdown table -> html works properly right? (or I am very lucky and it works in my instance). The problem happens when from an existing html table we want to have the markdown, right?
